version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Instalando dependencias..."
      - pip install -r app/requirements.txt
  build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/app
      - pytest tests/
  post_build:
    commands:
      - echo "Construcción finalizada con éxito"
